# Generated by Django 4.0.4 on 2022-04-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patientCPF', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=100)),
                ('patientAge', models.IntegerField()),
                ('patientRG', models.CharField(max_length=20)),
                ('patientBirth', models.DateField()),
                ('patientSex', models.CharField(max_length=20)),
                ('patientSign', models.CharField(max_length=50)),
                ('patientMom', models.CharField(max_length=100)),
                ('patientFather', models.CharField(max_length=100)),
                ('patientEmail', models.CharField(max_length=100)),
                ('patientsPassword', models.CharField(max_length=100)),
                ('patientCep', models.CharField(max_length=10)),
                ('patientAdress', models.CharField(max_length=100)),
                ('patientAdressNumber', models.IntegerField()),
                ('patientAdressNeighborhood', models.CharField(max_length=100)),
                ('patientCity', models.CharField(max_length=100)),
                ('patientState', models.CharField(max_length=100)),
                ('patientHPhone', models.CharField(max_length=20)),
                ('patientPhone', models.CharField(max_length=20)),
                ('patientHeight', models.CharField(max_length=20)),
                ('patientWeight', models.IntegerField()),
                ('patientBlood', models.CharField(max_length=10)),
                ('patientColor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientsCardiac',
            fields=[
                ('patientCPF', models.AutoField(primary_key=True, serialize=False)),
                ('patientDate', models.CharField(max_length=10)),
                ('patientCEPOC', models.CharField(max_length=100)),
                ('patientInd_card', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientsPulmonary',
            fields=[
                ('patientCPF', models.AutoField(primary_key=True, serialize=False)),
                ('patientDate', models.CharField(max_length=10)),
                ('patientPEPOC', models.CharField(max_length=100)),
                ('patientInd_pulm', models.FloatField()),
            ],
        ),
    ]
