# Generated by Django 4.0.4 on 2022-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscardiac',
            name='patientDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientspulmonary',
            name='patientDate',
            field=models.DateField(),
        ),
    ]
