# Generated by Django 4.0.4 on 2022-04-16 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalAPI', '0002_alter_patientscardiac_patientdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscardiac',
            name='id',
            field=models.BigAutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientspulmonary',
            name='id',
            field=models.BigAutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientscardiac',
            name='patientCPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPI.patients'),
        ),
        migrations.AlterField(
            model_name='patientspulmonary',
            name='patientCPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPI.patients'),
        ),
    ]
