# Generated by Django 4.0.4 on 2022-04-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalAPI', '0004_rename_patientheight_patients_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='patientscardiac',
            name='patientCPF',
            field=models.ForeignKey(db_column='patientCPF', on_delete=django.db.models.deletion.CASCADE, to='HospitalAPI.patients', to_field='cpf'),
        ),
        migrations.AlterField(
            model_name='patientspulmonary',
            name='patientCPF',
            field=models.ForeignKey(db_column='patientCPF', on_delete=django.db.models.deletion.CASCADE, to='HospitalAPI.patients', to_field='cpf'),
        ),
    ]
