# Generated by Django 4.0.4 on 2022-04-19 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalAPI', '0007_alter_patientscardiac_patientcpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscardiac',
            name='patientCPF',
            field=models.ForeignKey(blank=True, db_column='cpf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardiac', to='HospitalAPI.patients', to_field='cpf'),
        ),
        migrations.AlterField(
            model_name='patientspulmonary',
            name='patientCPF',
            field=models.ForeignKey(blank=True, db_column='cpf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pulmonary', to='HospitalAPI.patients', to_field='cpf'),
        ),
    ]
