# Generated by Django 4.0.4 on 2022-04-19 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalAPI', '0009_alter_patientscardiac_patientcpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscardiac',
            name='patientCPF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientCPF', to='HospitalAPI.patients', to_field='cpf'),
        ),
    ]
