# Generated by Django 4.0.4 on 2022-04-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalAPI', '0010_alter_patientscardiac_patientcpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscardiac',
            name='patientCPF',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='cardiac', to='HospitalAPI.patients', to_field='cpf'),
            preserve_default=False,
        ),
    ]
